# Generated by Django 4.1.1 on 2022-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='team_pics')),
                ('team_name', models.CharField(max_length=250)),
                ('team_desc', models.TextField()),
            ],
        ),
    ]
