# Generated by Django 4.1.1 on 2022-10-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
